### ISSUE TITLE
Add docker images building instructions to README.md

### ISSUE THREAD

**Issue by earthquakesan** [hobbit-project/odin#6]
According to the [this manual](https://github.com/hobbit-project/platform/wiki/Upload-a-system) the docker images should already exist somewhere. This repo is missing instructions on how to build docker images. Please add.

**Comment by Kleanthi** [comment]
The docker images described in the aforementioned manual refer to the system that will be benchmarked not the benchmark itself. I agree that there should be a manual and documentation for creating docker files for systems, but for the benchmark itself, there is no point. So this issue is not related to odin. I am closing it.

**Comment by earthquakesan** [comment]
Why there is no point in the manual for creating docker images for the benchmark? 
In case if someone not from HOBBIT project wants to install the platform they should be able to build and upload the benchmarks.
@MichaelRoeder we need your opinion on this one. Am I missing here something?

**Comment by MichaelRoeder** [comment]
I agree with @earthquakesan

**Comment by Kleanthi** [comment]
done
